# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-30 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, verbose_name='document_identity')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('lastname', models.CharField(max_length=30, verbose_name='lastname')),
                ('celphone_contact', models.CharField(max_length=50, verbose_name='number_phone')),
                ('address', models.CharField(max_length=100, verbose_name='personal_address')),
            ],
            options={
                'ordering': ['lastname'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('lat', models.CharField(max_length=20, verbose_name='latitude')),
                ('length', models.CharField(max_length=20, verbose_name='length')),
                ('price', models.IntegerField(verbose_name='price')),
                ('person_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='apirest.Person')),
            ],
        ),
    ]
