# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-06 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0002_auto_20180106_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='prop_type',
            field=models.CharField(blank=True, choices=[('d', 'departament'), ('h', 'house'), ('l', 'local')], help_text='Tipo de Local', max_length=1),
        ),
    ]
